# ---------- Stage 1: Build ----------
FROM node:18-alpine AS build

WORKDIR /frontend

COPY ./frontend/package*.json ./
RUN npm ci

COPY ./frontend/ ./
RUN npm run build


# ---------- Stage 2: Serve ----------
FROM nginx:alpine

COPY --from=build /frontend/dist /usr/share/nginx/html

# optional custom config
# COPY ./deploy/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]